components:
    schemas:
        CreateDailyTripRequest:
            properties:
                Date:
                    type: string
                Day:
                    type: string
                Notes:
                    type: string
                TripId:
                    type: string
            type: object
        CreateDailyTripResponse:
            properties:
                DailyTrip:
                    type: string
            type: object
        CreateTripRequest:
            properties:
                Description:
                    type: string
                EndTs:
                    type: string
                StartTs:
                    type: string
                Title:
                    type: string
            type: object
        CreateTripResponse:
            properties:
                Trip:
                    type: string
            type: object
        DeleteDailyTripRequest:
            properties:
                DailyId:
                    type: string
                TripId:
                    type: string
            type: object
        DeleteDailyTripResponse:
            properties:
                Status:
                    type: string
            type: object
        DeleteTripRequest:
            properties:
                Id:
                    type: string
            type: object
        DeleteTripResponse:
            properties:
                Status:
                    type: string
            type: object
        GetDailyTripRequest:
            properties:
                DailyId:
                    type: string
                TripId:
                    type: string
            type: object
        GetDailyTripResponse:
            properties:
                DailyTrip:
                    type: string
            type: object
        GetSmsAuthTokensRequest:
            properties: {}
            type: object
        GetSmsAuthTokensResponse:
            properties:
                BizToken:
                    type: string
                ExpireTime:
                    type: string
                StsAccessKeyId:
                    type: string
                StsAccessKeySecret:
                    type: string
                StsToken:
                    type: string
            type: object
        GetTripRequest:
            properties:
                Id:
                    type: string
            type: object
        GetTripResponse:
            properties:
                Trip:
                    type: string
            type: object
        ListDailyTripsRequest:
            properties:
                TripId:
                    type: string
            type: object
        ListDailyTripsResponse:
            properties:
                DailyTrips:
                    type: string
            type: object
        ListTripsRequest:
            properties: {}
            type: object
        ListTripsResponse:
            properties:
                Trips:
                    type: string
            type: object
        RefreshTokenRequest:
            properties:
                RefreshToken:
                    type: string
            type: object
        RefreshTokenResponse:
            properties:
                ExpiresIn:
                    type: string
                Token:
                    type: string
            type: object
        RequestPasswordResetRequest:
            properties:
                Email:
                    type: string
            type: object
        RequestPasswordResetResponse:
            properties:
                Status:
                    type: string
            type: object
        ResetPasswordRequest:
            properties:
                NewPassword:
                    type: string
                Token:
                    type: string
            type: object
        ResetPasswordResponse:
            properties:
                Status:
                    type: string
            type: object
        SignInRequest:
            properties:
                Email:
                    type: string
                Password:
                    type: string
            type: object
        SignInResponse:
            properties:
                ExpiresIn:
                    type: string
                RefreshToken:
                    type: string
                Token:
                    type: string
            type: object
        SignInWithOAuthRequest:
            properties:
                Code:
                    type: string
                Provider:
                    type: string
            type: object
        SignInWithOAuthResponse:
            properties:
                Token:
                    type: string
            type: object
        SignUpRequest:
            properties:
                Email:
                    type: string
                Password:
                    type: string
            type: object
        SignUpResponse:
            properties:
                ExpiresIn:
                    type: string
                RefreshToken:
                    type: string
                Token:
                    type: string
            type: object
        UpdateDailyTripRequest:
            properties:
                DailyId:
                    type: string
                Date:
                    type: string
                Day:
                    type: string
                Notes:
                    type: string
                TripId:
                    type: string
            type: object
        UpdateDailyTripResponse:
            properties:
                DailyTrip:
                    type: string
            type: object
        UpdateTripRequest:
            properties:
                Description:
                    type: string
                EndTs:
                    type: string
                Id:
                    type: string
                StartTs:
                    type: string
                Status:
                    type: string
                Title:
                    type: string
            type: object
        UpdateTripResponse:
            properties:
                Trip:
                    type: string
            type: object
        VerifyPasswordResetTokenRequest:
            properties:
                Token:
                    type: string
            type: object
        VerifyPasswordResetTokenResponse:
            properties:
                Valid:
                    type: string
            type: object
        VerifySmsCodeRequest:
            properties:
                PhoneNumber:
                    type: string
                SmsCode:
                    type: string
                SmsToken:
                    type: string
            type: object
        VerifySmsCodeResponse:
            properties:
                ExpiresIn:
                    type: string
                Token:
                    type: string
            type: object
info:
    description: API generated from protobufs
    title: Generated API
    version: 1.0.0
openapi: 3.0.0
paths:
    /api/v1/auth/refresh-token:
        post:
            operationId: AuthService_RefreshToken
            requestBody:
                content:
                    application/json:
                        schema:
                            $ref: '#/components/schemas/RefreshTokenRequest'
            responses:
                "200":
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/RefreshTokenRequest'
                    description: Successful Response
            tags:
                - AuthService
    /api/v1/auth/request-password-reset:
        post:
            operationId: AuthService_RequestPasswordReset
            requestBody:
                content:
                    application/json:
                        schema:
                            $ref: '#/components/schemas/RequestPasswordResetRequest'
            responses:
                "200":
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/RequestPasswordResetRequest'
                    description: Successful Response
            tags:
                - AuthService
    /api/v1/auth/reset-password:
        post:
            operationId: AuthService_ResetPassword
            requestBody:
                content:
                    application/json:
                        schema:
                            $ref: '#/components/schemas/ResetPasswordRequest'
            responses:
                "200":
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/ResetPasswordRequest'
                    description: Successful Response
            tags:
                - AuthService
    /api/v1/auth/sign-in/oauth:
        post:
            operationId: AuthService_SignInWithOAuth
            requestBody:
                content:
                    application/json:
                        schema:
                            $ref: '#/components/schemas/SignInWithOAuthRequest'
            responses:
                "200":
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/SignInWithOAuthRequest'
                    description: Successful Response
            tags:
                - AuthService
    /api/v1/auth/sign-in/password:
        post:
            operationId: AuthService_SignIn
            requestBody:
                content:
                    application/json:
                        schema:
                            $ref: '#/components/schemas/SignInRequest'
            responses:
                "200":
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/SignInRequest'
                    description: Successful Response
            tags:
                - AuthService
    /api/v1/auth/sign-up:
        post:
            operationId: AuthService_SignUp
            requestBody:
                content:
                    application/json:
                        schema:
                            $ref: '#/components/schemas/SignUpRequest'
            responses:
                "200":
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/SignUpRequest'
                    description: Successful Response
            tags:
                - AuthService
    /api/v1/auth/sms-auth-tokens:
        post:
            operationId: AuthService_GetSmsAuthTokens
            requestBody:
                content:
                    application/json:
                        schema:
                            $ref: '#/components/schemas/GetSmsAuthTokensRequest'
            responses:
                "200":
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/GetSmsAuthTokensRequest'
                    description: Successful Response
            tags:
                - AuthService
    /api/v1/auth/verify-password-reset-token:
        get:
            operationId: AuthService_VerifyPasswordResetToken
            requestBody:
                content:
                    application/json:
                        schema:
                            $ref: '#/components/schemas/VerifyPasswordResetTokenRequest'
            responses:
                "200":
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/VerifyPasswordResetTokenRequest'
                    description: Successful Response
            tags:
                - AuthService
    /api/v1/auth/verify-sms-code:
        post:
            operationId: AuthService_VerifySmsCode
            requestBody:
                content:
                    application/json:
                        schema:
                            $ref: '#/components/schemas/VerifySmsCodeRequest'
            responses:
                "200":
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/VerifySmsCodeRequest'
                    description: Successful Response
            tags:
                - AuthService
    /api/v1/trips:
        get:
            operationId: TripService_ListTrips
            requestBody:
                content:
                    application/json:
                        schema:
                            $ref: '#/components/schemas/ListTripsRequest'
            responses:
                "200":
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/ListTripsRequest'
                    description: Successful Response
            tags:
                - TripService
    /api/v1/trips/{id}:
        delete:
            operationId: TripService_DeleteTrip
            requestBody:
                content:
                    application/json:
                        schema:
                            $ref: '#/components/schemas/DeleteTripRequest'
            responses:
                "200":
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/DeleteTripRequest'
                    description: Successful Response
            tags:
                - TripService
    /api/v1/trips/{trip_id}/daily:
        get:
            operationId: TripService_ListDailyTrips
            requestBody:
                content:
                    application/json:
                        schema:
                            $ref: '#/components/schemas/ListDailyTripsRequest'
            responses:
                "200":
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/ListDailyTripsRequest'
                    description: Successful Response
            tags:
                - TripService
    /api/v1/trips/{trip_id}/daily/{daily_id}:
        delete:
            operationId: TripService_DeleteDailyTrip
            requestBody:
                content:
                    application/json:
                        schema:
                            $ref: '#/components/schemas/DeleteDailyTripRequest'
            responses:
                "200":
                    content:
                        application/json:
                            schema:
                                $ref: '#/components/schemas/DeleteDailyTripRequest'
                    description: Successful Response
            tags:
                - TripService
